const cards = {
  "3rdRaikage_argent_ultra_s_800k.jpg": "https://files.catbox.moe/7c3pgw.jpg",
  "A_argent_ultra_sm_600k.jpg": "https://files.catbox.moe/amfh8w.jpg",
  "Ace_bronze_sparking_sp_400k.jpg": "https://files.catbox.moe/5vqryh.jpg",
  "Acnologia_or_legend_sm_1M.jpg": "https://files.catbox.moe/dy20sv.jpg",
  "Aiolia_or_sparking_sm_1M.jpg": "https://files.catbox.moe/2mbwpb.jpg",
  "Akainu_argent_ultra_sp_800k.jpg": "https://files.catbox.moe/qgrflk.jpg",
  "Akaza_bronze_ultra_sp_450k.jpg": "https://files.catbox.moe/o8waf7.jpg",
  "Aldebaran_or_sparking_sm_1M.jpg": "https://files.catbox.moe/nvdw2s.jpg",
  "AllForOne_or_legend_sm_1m.jpg": "https://files.catbox.moe/u18ovi.jpg",
  "AllMight_or_legend_sm_1m.jpg": "https://files.catbox.moe/3x7bn9.jpg",
  "Android16_bronze_sparking_ssp_100nc.jpg": "https://files.catbox.moe/tt79m2.jpg",
  "Android17(Dbz)_argent _legend_ss_200nc.jpg": "https://files.catbox.moe/hohfci.jpg",
  "Android17(Dbs)_or_ultra_ssp_420nc.jpg": "https://files.catbox.moe/4bl67g.jpg",
  "Android18_argent_legend_ss_190nc.jpg": "https://files.catbox.moe/b7neim.jpg",
  "Android19_bronze_sparking_ssp_90nc.jpg": "https://files.catbox.moe/1lao5m.jpg",
  "Aoi_bronze_ultra_s_350k.jpg": "https://files.catbox.moe/0rocs7.jpg",
  "Aokiji_argent_ultra_sp_800k.jpg": "https://files.catbox.moe/dhy54u.jpg",
  "Aphrodite_or_sparking_sm_1M.jpg": "https://files.catbox.moe/fairbf.jpg",
  "Asta_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/tjsj81.jpg",
  "Asta(Arc2)_bronze_ultra_sp_450k.jpg": "https://files.catbox.moe/2cd5ht.jpg",
  "Asuma_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/e9h4s7.jpg",
  "AtomicSamurai_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/ihy73q.jpg",
  "Avdol_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/wgv1t5.jpg",
  "BabyVegeta_or_sparking_ssm_310nc.jpg": "https://files.catbox.moe/ahxz48.jpg",
  "Bakugo_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/gz77gh.jpg",
  "Bang_bronze_Legend_sp_450k.jpg": "https://files.catbox.moe/yis1od.jpg",
  "Beerus_or_legend_ssp_530nc.jpg": "https://files.catbox.moe/y9cgpo.jpg",
  "Bigmom_argent_legend_sm_1M.jpg": "https://files.catbox.moe/8qo8yi.jpg",
  "BlackGoku_or_legend_ssp_460nc.jpg": "https://files.catbox.moe/un7c3l.jpg",
  "Blizzard_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/q3qznx.jpg",
  "Bojack_argent_sparking_ssm_120nc.jpg": "https://files.catbox.moe/ck3vpk.jpg",
  "Boro_argent_sparking_s_700k.jpg": "https://files.catbox.moe/bokgxn.jpg",
  "Boros_or_legend_sp_2M.jpg": "https://files.catbox.moe/ofoqc5.jpg",
  "Borushiki_argent_legend_sp_800k.jpg": "https://files.catbox.moe/ayb8n5.jpg",
  "Boruto_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/8qzmzr.jpg",
  "Broly_argent_legend_ssp_300nc.jpg": "https://files.catbox.moe/au0pd6.jpg",
  "Broly(Dbs)_or_legend_ssp_480nc.jpg": "https://files.catbox.moe/2qvkfx.jpg",
  "Brooks_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/kf359g.jpg",
  "Buhan_or_legend_ss_340nc.jpg": "https://files.catbox.moe/2tbn9y.jpg",
  "Burter_bronze_sparking_ssp_90nc.jpg": "https://files.catbox.moe/jkx88l.jpg",
  "Buu(super)_or_sparking_ssm_310nc.jpg": "https://files.catbox.moe/5lfqpz.jpg",
  "Buu(Fat)_or_sparking_ssm_300nc.jpg": "https://files.catbox.moe/xnl4el.jpg",
  "Buu(Kid)_or_legend_ssm_360nc_.jpg": "https://files.catbox.moe/bb2e50.jpg",
  "Buutenks_or_ultra_ssm_320nc.jpg": "https://files.catbox.moe/1gcugi.jpg",
  "Cabba_bronze_sparking_ssp_130nc.jpg": "https://files.catbox.moe/rkdbjj.jpg",
  "Caufila_argent_sparking_ss_200nc.jpg": "https://files.catbox.moe/36yixr.jpg",
  "Cell(perfect)_argent_legend_ssp_280nc.jpg": "https://files.catbox.moe/3vv40w.jpg",
  "Cell(super)_argent_sparking_ss_210nc.jpg": "https://files.catbox.moe/6mi2yw.jpg",
  "Cell(base)_bronze_sparking_ssp_100nc.jpg": "https://files.catbox.moe/xsh1ot.jpg",
  "Chiyo_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/5m69a3.jpg",
  "Choji_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/caghzt.jpg",
  "Choso_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/ww982g.jpg",
  "Chrollo_argent_ultra_sm_500k.jpg": "https://files.catbox.moe/jpuv9q.jpg",
  "Code_argent_ultra_sm_500k.jpg": "https://files.catbox.moe/bhq7oh.jpg",
  "Code(TBV)_or_sparking_s_1M200k.jpg": "https://files.catbox.moe/3vhh0l.jpg",
  "Crocodile_bronze_sparking_sp_400k.jpg": "https://files.catbox.moe/s8yttz.jpg",
  "Dabi_bronze_ultra_sp_400k.jpg": "https://files.catbox.moe/mjb4lj.jpg",
  "Dabura_argent_sparking_ssp_250nc.jpg": "https://files.catbox.moe/edan2e.jpg",
  "Daemon_or_legend_s_1M800k.jpg": "https://files.catbox.moe/s0sucf.jpg",
  "Dagon_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/cp5op5.jpg",
  "Daki_bronze_sparking_sm_150k.jpg": "https://files.catbox.moe/14j5af.jpg",
  "Dante_or_ultra_sm_1m.jpg": "https://files.catbox.moe/n4dlb1.jpg",
  "Danzo_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/jve2vt.jpg",
  "Darui_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/zs80ob.jpg",
  "Deathmask_or_sparking_s_1M500k.jpg": "https://files.catbox.moe/m6zwzi.jpg",
  "DeepSeaKing_argent_sparking_s_700k.jpg": "https://files.catbox.moe/yqiviz.jpg",
  "Deepa_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/epjakr.jpg",
  "Deidara_bronze_ultra_s_300k.jpg": "https://files.catbox.moe/m0wm1s.jpg",
  "DekuRogueHero_argent_ultra_s_700k.jpg": "https://files.catbox.moe/z5hzqb.jpg",
  "Deku_bronze_ultra_s_300k.jpg": "https://files.catbox.moe/oh99hl.jpg",
  "Delta_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/h68hzb.jpg",
  "Denki_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/xerqh0.jpg",
  "Diavolo_argent_ultra_sm_900k.jpg": "https://files.catbox.moe/yw5xb8.jpg",
  "Dio_argent_legend_s_900k.jpg": "https://files.catbox.moe/32pw7w.jpg",
  "Doflamingo_argent_ultra_sm_550k.jpg": "https://files.catbox.moe/v126vu.jpg",
  "Doma_bronze_ultra_s_300k.jpg": "https://files.catbox.moe/4xdikn.jpg",
  "Dr.Gero_bronze_sparking_sp_600k.jpg": "https://files.catbox.moe/glg41l.jpg",
  "Dyspo_or_sparking_ssp_400nc.jpg": "https://files.catbox.moe/tr27u0.jpg",
  "Edward_argent_legend_sp_1M200k.jpg": "https://files.catbox.moe/q5bapo.jpg",
  "Eida_or_legend_s_1M800k.jpg": "https://files.catbox.moe/5tx64p.jpg",
  "Eijiro_bronze_sparking_sm_100k.jpg.jpg": "https://files.catbox.moe/ljz7bk.jpg",
  "Endeavor_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/qcunun.jpg",
  "Enmu_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/x4hsa6.jpg",
  "Erza_bronze_ultra_sp_450k.jpg": "https://files.catbox.moe/otsr2e.jpg",
  "FlashyFlash_argent_sparking_s_700k.jpg": "https://files.catbox.moe/git5xh.jpg",
  "Franky_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/t46wfj.jpg",
  "Frieza(super)_argent_legend_ssm_160nc.jpg": "https://files.catbox.moe/l97ml8.jpg",
  "Frieza(Base)_bronze_ultra_ssp_150nc.jpg": "https://files.catbox.moe/i84paz.jpg",
  "Frieza(Golden)_or_sparking_ssp_420nc.jpg": "https://files.catbox.moe/dptorv.jpg",
  "Fuegoleon_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/2ocv94.jpg",
  "Fujitora_argent_ultra_s_700k.jpg": "https://files.catbox.moe/fslosy.jpg",
  "Fumikage_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/mucucs.jpg",
  "Gaara_bronze_ultra_s_400k.jpg": "https://files.catbox.moe/v3nvkj.jpg",
  "Gaara_bronze_ultra_sm_300k.jpg": "https://files.catbox.moe/cto2vg.jpg",
  "Gajeel_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/8j1xus.jpg",
  "Garou_bronze_legend_sp_450k.jpg": "https://files.catbox.moe/hbdp8l.jpg",
  "GarouMonster_argent_legend_sm_500k.jpg": "https://files.catbox.moe/joebj6.jpg",
  "Garou(cosmic)_or_ultra_ssm_200nc.jpg": "https://files.catbox.moe/6qyvrq.jpg",
  "Garp_argent_ultra_s_800k.jpg": "https://files.catbox.moe/20h2tl.jpg",
  "Gauche_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/7gv4r9.jpg",
  "Gengetsu_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/77h87l.jpg",
  "Genos(forme 2)_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/0p7zf7.jpg",
  "Genos_bronze_ultra_s_300k.jpg": "https://files.catbox.moe/yvk9j3.jpg",
  "Geto_bronze_ultra_sp_400k.jpg": "https://files.catbox.moe/ytx8vy.jpg",
  "Geto(student)_bronze_ultra_s_350k.jpg": "https://files.catbox.moe/0o4is7.jpg",
  "Gildarts_argent_ultra_sp_900k.jpg": "https://files.catbox.moe/41g7x4.jpg",
  "Ginyu_bronze_sparking_ssp_100nc.jpg": "https://files.catbox.moe/1nhx0y.jpg",
  "Giorno_or_legende_sm_1M200k.jpg": "https://files.catbox.moe/5wvjc1.jpg",
  "Giyu_bronze_ultra_s_300k.jpg": "https://files.catbox.moe/7ehtyz.jpg",
  "Gogeta(Dbz)_or_legend_ssp_450nc.jpg": "https://files.catbox.moe/ddf764.jpg",
  "Gogeta(Dbs)_or_legend_ssp_550nc.jpg": "https://files.catbox.moe/ru0r9d.jpg",
  "Gogeta(SSJ4)_or_sparking_ssp_460nc.jpg": "https://files.catbox.moe/agk0gp.jpg",
  "Gohan(Beast)_or_legend_ssp_550nc.jpg": "https://files.catbox.moe/aj97ba.jpg",
  "Gohan(Futur)_argent_legend_ss_190nc.jpg": "https://files.catbox.moe/ghl7so.jpg",
  "Gohan(SSj2)_argent_legend_ssp_290nc.jpg": "https://files.catbox.moe/ym9696.jpg",
  "Gohan(SSJ)_argent_sparking_ssm_150nc.jpg": "https://files.catbox.moe/d39zp8.jpg",
  "Gohan(Buu arc)_argent_sparking_ssp_260nc.jpg": "https://files.catbox.moe/r3za80.jpg",
  "Gohan(Kid)_bronze_sparking_sp_90nc.jpg": "https://files.catbox.moe/3b7ypn.jpg",
  "Gohan(ultime)_or_legend_ssm_350nc.jpg": "https://files.catbox.moe/arcs79.jpg",
  "Gohan(Dbs)_or_legend_ssp_430nc.jpg": "https://files.catbox.moe/gfnu6y.jpg",
  "Gojo_argent_legend_s_800k.jpg": "https://files.catbox.moe/3hmg8k.jpg",
  "Gojo(shinjuku)_argent_legend_sp_100nc.jpg": "https://files.catbox.moe/jg1bvq.jpg",
  "Gojo(Student)_bronze_legend_sp_50nc.jpg": "https://files.catbox.moe/qnha9o.jpg",
  "Goku(SSJnamek)_argent_legend_ssm_180nc.jpg": "https://files.catbox.moe/l4lt5w.jpg",
  "Goku(androids)_argent_legend_ssp_270nc.jpg": "https://files.catbox.moe/fpkm2x.jpg",
  "Goku(SSJ2)_argent_legend_ssp_290nc.jpg": "https://files.catbox.moe/0ib3ua.jpg",
  "Goku(name)_bronze_legend_ssp_150nc.jpg": "https://files.catbox.moe/vp7t7k.jpg",
  "Goku(debut)_bronze_sparking_ssm_100nc.jpg": "https://files.catbox.moe/bxvdah.jpg",
  "Goku(saiyans)_bronze_sparking_ssp_130nc.jpg": "https://files.catbox.moe/m9tieb.jpg",
  "Goku(SSJBlue)_or_legend_spp_450nc.jpg": "https://files.catbox.moe/00ehxc.jpg",
  "Goku(SSJ4)_or_legend_ss_350nc.jpg": "https://files.catbox.moe/cz69qw.jpg",
  "Goku(UI)_or_legend_ssp_500nc.jpg": "https://files.catbox.moe/kt9847.jpg",
  "Goku(UIM)_or_legend_ssp_550nc.jpg": "https://files.catbox.moe/u7bja5.jpg",
  "Goku(SSJGod)_or_ultra_ssp_420nc.jpg": "https://files.catbox.moe/54ri6n.jpg",
  "Gon_bronze_ultra_sp_450k.jpg": "https://files.catbox.moe/ry2s2p.jpg",
  "Goten_argent_sparking_ssm_150nc.jpg": "https://files.catbox.moe/lstklv.jpg",
  "Gotunks_argent_ultra_ssp_280nc.jpg": "https://files.catbox.moe/cmwm6d.jpg",
  "Gray_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/p0m71h.jpg",
  "Guy(4GG)_argent_ultra_s_600k.jpg": "https://files.catbox.moe/ydickg.jpg",
  "Gyokko_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/z5ma7e.jpg",
  "Gyomei_bronze_ultra_sp_400k.jpg": "https://files.catbox.moe/2zgiik.jpg",
  "Gyotaro_bronze_sparking_sm_150k.jpg": "https://files.catbox.moe/iefaij.jpg",
  "Hades_or_legend_ssp_500nc.jpg": "https://files.catbox.moe/12yij9.jpg",
  "Hakari_bronze_ultra_sp_400k.jpg": "https://files.catbox.moe/2k6dyk.jpg",
  "Haku_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/iqzqpd.jpg",
  "Hanami_bronze_sparking_sp_400k.jpg": "https://files.catbox.moe/s8ajn1.jpg",
  "Hanzo_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/bfepmy.jpg",
  "Haruta_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/plkxqq.jpg",
  "Hashirama(Alive)_argent_legend_sp_1m300k.jpg": "https://files.catbox.moe/vom5wp.jpg",
  "Hashirama(Edo)_argent_legend_sp_1m500k.jpg": "https://files.catbox.moe/08zqem.jpg",
  "Hawk_bronze_sparking_s_400k.jpg": "https://files.catbox.moe/enl424.jpg",
  "Hidan_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/896un5.jpg",
  "Higuruma_bronze_sparking_sm_150k.jpg": "https://files.catbox.moe/e3cqou.jpg",
  "Hinata_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/l7bwxg.jpg",
  "Hiruzen_argent_sparking_sm_600k.jpg": "https://files.catbox.moe/e15qos.jpg",
  "Hisoka_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/z2ku4m.jpg",
  "Hit_or_ultra_ssp_430nc.jpg": "https://files.catbox.moe/3t3uzr.jpg",
  "HommeMasqué_argent_legend_sm_600k.jpg": "https://files.catbox.moe/sccdyw.jpg",
  "Hyoga_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/eqbudy.jpg",
  "Hypnos_or_legend_ssp_400nc.jpg": "https://files.catbox.moe/9k7vjk.jpg",
  "Sukuna(4F)_bronze_legend_sp_50nc.jpg": "https://files.catbox.moe/bozoos.jpg",
  "Sukuna(19F)_argent_legend__sp_100nc.jpg": "https://files.catbox.moe/4v8ltt.jpg",
  "Sukuna(Shibuya)_argent_legend_s_800k.jpg": "https://files.catbox.moe/ayhiwq.jpg",
  "Sukuna(Heian)_argent_legend_sp_100nc.jpg": "https://files.catbox.moe/cio9my.jpg",
  "Ikki_argent_ultra_sp_950k.jpg": "https://files.catbox.moe/5s7uwj.jpg",
  "Ino_bronze_sparking_sm_100K.jpg": "https://files.catbox.moe/0spc1o.jpg",
  "Ino(JJK)_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/cg2wxw.jpg",
  "Inojin_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/23wvgt.jpg",
  "Inosuke_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/8zmkr0.jpg",
  "Ishiki_or_legend_sp_2M.jpg": "https://files.catbox.moe/m6vjmz.jpg",
  "Itachi_argent_legend_sm_600k.jpg": "https://files.catbox.moe/f0nd4b.jpg",
  "Itachi(Edo)_argent_ultra_s_700k.jpg": "https://files.catbox.moe/xpzn76.jpg",
  "JackTheRipper_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/f78k47.jpg",
  "Janemba_or_ultra_ssp_300nc.jpg": "https://files.catbox.moe/90dppi.jpg",
  "Jeece_bronze_sparking_ssp_90nc.jpg": "https://files.catbox.moe/razec6.jpg",
  "Jellal_argent_ultra_sm_550k.jpg": "https://files.catbox.moe/ru57o0.jpg",
  "Jigen_or_legend_s_1M500k.jpg": "https://files.catbox.moe/mwdvg4.jpg",
  "Jimbei_bronze_sparking_sp_400k.jpg": "https://files.catbox.moe/fmwot7.jpg",
  "Jiraya_bronze_ultra_sp_450k.jpg": "https://files.catbox.moe/2gijaq.jpg",
  "Jiren_or_legend_ssp_550nc.jpg": "https://files.catbox.moe/ox8j94.jpg",
  "Jogo_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/ul7qbm.jpg",
  "Jotaro_argent_legend_sm_800k.jpg": "https://files.catbox.moe/3axyi1.jpg",
  "Jugo_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/fw3z6n.jpg",
  "Julius_or_legend_s_1m500k.jpg": "https://files.catbox.moe/r51fdi.jpg",
  "Kabuto(Ermite)_argent_legend_s_800k.jpg": "https://files.catbox.moe/71wcyi.jpg",
  "Kabuto_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/0entih.jpg",
  "Kaguya_or_legend_sp_2m.jpg": "https://files.catbox.moe/09aavm.jpg",
  "Kaido_argent_legend_sp_1M.jpg": "https://files.catbox.moe/jpfezg.jpg",
  "Kaigaku_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/fx8882.jpg",
  "Kakashi(4GG)_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/v15u2p.jpg",
  "Kakashi(Ado)_bronze_sparking_sm_150k.jpg": "https://files.catbox.moe/yht6x6.jpg",
  "Kakashi_bronze_ultra_sp_400k.jpg": "https://files.catbox.moe/cd4vqa.jpg",
  "Kakuzu_bronze_ultra_sp_400k.jpg": "https://files.catbox.moe/u0srbo.jpg",
  "Kakyoin_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/gq9ncc.jpg",
  "Kale_argent_sparking_ssp_280nc.jpg": "https://files.catbox.moe/rf7tpo.jpg",
  "Kamo_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/ux5uaa.jpg",
  "Kanao_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/zfk7bs.jpg",
  "Kankuro_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/qezt29.jpg",
  "Kashimo_argent_ultra_sm_500k.jpg": "https://files.catbox.moe/nwl69h.jpg",
  "Kashin_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/s60eyv.jpg",
  "Katakuri_argent_ultra_s_800k.jpg": "https://files.catbox.moe/w1ai58.jpg",
  "Kawaki_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/wo4hxm.jpg",
  "Kawashiki_argent_legende_sp_800k.jpg": "https://files.catbox.moe/2equyh.jpg",
  "Kefla_or_ultra_ssp_480nc.jpg": "https://files.catbox.moe/lg1241.jpg",
  "Kenjaku_argent_ultra_sm_500k.jpg": "https://files.catbox.moe/4fph85.jpg",
  "Kiba_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/i9utly.jpg",
  "Kid_bronze_ultra_sp_450k.jpg": "https://files.catbox.moe/uli7li.jpg",
  "Killerbee_argent_ultra_sm_600k.jpg": "https://files.catbox.moe/rt3jgx.jpg",
  "Kilua_argent_ultra_sm_500k.jpg": "https://files.catbox.moe/v9gws9.jpg",
  "Kimimaro_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/1z659k.jpg",
  "Kisame_agrent_ultra_sm_600k.jpg": "https://files.catbox.moe/86r0s0.jpg",
  "Kizaru_or_sparking_sm_1M.jpg": "https://files.catbox.moe/tffpmi.jpg",
  "Kokushibo_argent_legend_sm_50nc.jpg": "https://files.catbox.moe/c4upfm.jpg",
  "Konan_bronze_sparking_sm_200k.jpg": "https://files.catbox.moe/xiw3r5.jpg",
  "Konohamaru_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/gkkvrj.jpg",
  "Krillin_bronze_sparking_sp_500k.jpg": "https://files.catbox.moe/zvmx6x.jpg",
  "Kurapika_bronze_ultra_s_300k.jpg": "https://files.catbox.moe/xtjdm3.jpg",
  "Kusakabe_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/i5iqnv.jpg",
  "Langris_bronze_ultra_s_300k.jpg": "https://files.catbox.moe/69ld8o.jpg",
  "Larue_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/uwo4at.jpg",
  "Law_bronze_ultra_s_350k.jpg": "https://files.catbox.moe/j60re6.jpg",
  "Laxus_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/c1znw5.jpg",
  "Lee_bronze_sparking_s_150k.jpg": "https://files.catbox.moe/m2r782.jpg",
  "Lemilion_bronze_sparking_sp_400k.jpg": "https://files.catbox.moe/d72cbu.jpg",
  "Leopold_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/qd65jc.jpg",
  "Licht_or_legend_sp_2m.jpg": "https://files.catbox.moe/y9fz3u.jpg",
  "Luck_bronze_ultra_s_350k.jpg": "https://files.catbox.moe/ggy08x.jpg",
  "Lucy_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/h05aul.jpg",
  "Luffy(wano)_argent_legend_s_1m.jpg": "https://files.catbox.moe/0mfgst.jpg",
  "Luffy_argent_ultra_sm_600k.jpg": "https://files.catbox.moe/o18qti.jpg",
  "Lyon_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/b0iaqz.jpg",
  "Madara(orange)_argent_legend_sm_600k.jpg": "https://files.catbox.moe/0ssw7d.jpg",
  "Madara(Edo)_argent_legend_sp_1M.jpg": "https://files.catbox.moe/unrace.jpg",
  "Madara(Rinnegan)_argent_legend_sp_1m.jpg": "https://files.catbox.moe/bpyee5.jpg",
  "Madara(Rebirth)_argent_legend_sp_1m500k.jpg": "https://files.catbox.moe/fr7lei.jpg",
  "Madara(Alive)_argent_sparking_sp_1m.jpg": "https://files.catbox.moe/thy0dm.jpg",
  "Madara(Rikudo)_or_legend_s_1m500k.jpg": "https://files.catbox.moe/zl2zrk.jpg",
  "Magna_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/xcel78.jpg",
  "Mahito_bronze_ultra_sm_350k.jpg": "https://files.catbox.moe/0dakux.jpg",
  "Mahito(Shibuya)_bronze_ultra_sp_400k.jpg": "https://files.catbox.moe/acd49z.jpg",
  "Mahoraga_argent_legend_sm_1m.jpg": "https://files.catbox.moe/3qr43l.jpg",
  "Mai_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/ok2814.jpg",
  "Vegeta(Majin)_argent_legend_ssp_290nc.jpg": "https://files.catbox.moe/rhx9q4.jpg",
  "Maki(Shinjuku)_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/xx854g.jpg",
  "Maki_bronze_ultra_s_300k.jpg": "https://files.catbox.moe/qi8e10.jpg",
  "Mechamaru_bronze_sparking_sm_150k.jpg": "https://files.catbox.moe/z0kfu2.jpg",
  "Megumi_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/91fz38.jpg",
  "MeiTerumi_bronze_sparking_sm_300k.jpg": "https://files.catbox.moe/kmdiht.jpg",
  "Mereleona_argent_ultra_sm_500k.jpg": "https://files.catbox.moe/044xjy.jpg",
  "Meruem_argent_legend_sp_1m.jpg": "https://files.catbox.moe/h1bm0w.jpg",
  "MetalBat_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/80fves.jpg",
  "Metallee_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/zq8yyk.jpg",
  "Mifune_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/3xj4g8.jpg",
  "Miguel_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/s0vkwy.jpg",
  "Mihawk_argent_legend_sp_1M.jpg": "https://files.catbox.moe/u89pdl.jpg",
  "Minato(Edo)_argent_legend_s_800k.jpg": "https://files.catbox.moe/mk0mgp.jpg",
  "Minato_argent_legend_sm_600k.jpg": "https://files.catbox.moe/q1yx82.jpg",
  "Minos_or_sparking_sp_2M.jpg": "https://files.catbox.moe/lmkfw4.jpg",
  "Mirko_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/idg38s.jpg",
  "Mitsuki_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/bktfvo.jpg",
  "Mitsuri_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/v5jnkh.jpg",
  "Miwa_bronze_sparking_sm_1000k.jpg": "https://files.catbox.moe/d15c8f.jpg",
  "Momo_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/9ckqpa.jpg",
  "Momo(JJK)_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/x6ozts.jpg",
  "Momoshiki_or_ultra_sm_1M200k.jpg": "https://files.catbox.moe/75hgce.jpg",
  "Mr.Satan_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/xkqt0d.jpg",
  "Muichiro_bronze_ultra_sp_400k.jpg": "https://files.catbox.moe/fcnlkr.jpg",
  "Muu_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/xn5cvq.jpg",
  "Muzan_argent_legend_smm_50nc.jpg": "https://files.catbox.moe/sv01h1.jpg",
  "Mû_or_legende_sm_1M.jpg": "https://files.catbox.moe/wuart5.jpg",
  "Nacht_bronze_ultra_sp_400k.jpg": "https://files.catbox.moe/wthf8r.jpg",
  "Nagato_agrent_legend_s_800k.jpg": "https://files.catbox.moe/9jvgu8.jpg",
  "Nami_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/eu6rue.jpg",
  "Nanami_bronze_sparking_sm_150k.jpg": "https://files.catbox.moe/exv4zk.jpg",
  "Naobito_bronze_sparking_s_250k.jpg": "https://files.catbox.moe/i9277v.jpg",
  "Naoya_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/svc0q3.jpg",
  "Nappa_bronze_sparking_ss_120nc.jpg": "https://files.catbox.moe/tg5ffy.jpg",
  "Naruto(KCM)_argent_legend_s_800k.jpg": "https://files.catbox.moe/j57927.jpg",
  "Naruto(KCM2)_argent_legend_sp_900k.jpg": "https://files.catbox.moe/lqpn2n.jpg",
  "Naruto(Ermite)_argent_ultra_sm_550k.jpg": "https://files.catbox.moe/1rr1dk.jpg",
  "Naruto_bronze_sparking_sm_300k.jpg": "https://files.catbox.moe/8qof2k.jpg",
  "Naruto(Thelast)_or_legend_sm_1m300k.jpg": "https://files.catbox.moe/u0y0kf.jpg",
  "Naruto(SP)_or_legend_sm_1m500k.jpg": "https://files.catbox.moe/dj0ex3.jpg",
  "Naruto(Hokage)_or_legend_sm_1M.jpg": "https://files.catbox.moe/372cj1.jpg",
  "Natsu_argent_ultra_sm_500k.jpg": "https://files.catbox.moe/l2gp0d.jpg",
  "Neji_bronze_sparking_s_150k.jpg": "https://files.catbox.moe/gtbyyb.jpg",
  "Nejire_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/hjestn.jpg",
  "Netero_argent _ultra_s_700k.jpg": "https://files.catbox.moe/qm6ts0.jpg",
  "Nezuko_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/o2oqnp.jpg",
  "Nobara_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/umse5q.jpg",
  "Noelle_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/3hn8s1.jpg",
  "Nozel_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/t1c2xd.jpg",
  "Obanai_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/dm3gua.jpg",
  "Obito(4GG)_argent_legend_s_800k.jpg": "https://files.catbox.moe/qqf4kv.jpg",
  "Obito(Ado)_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/fpmsiz.jpg",
  "Obito(Rage)_bronze_ultra_sp_500k.jpg": "https://files.catbox.moe/papag1.jpg",
  "Obito(Rikudo)_or_legend_sm_1m.jpg": "https://files.catbox.moe/czuvpu.jpg",
  "Ochaco_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/ps1o9h.jpg",
  "OmegaShenron_or_ultra_ssp_400nc.jpg": "https://files.catbox.moe/f2s078.jpg",
  "Onoki_bronze_legende_sp_500k.jpg": "https://files.catbox.moe/wm3pdr.jpg",
  "Orochimaru_bronze_ultra_sp_500k.jpg": "https://files.catbox.moe/h5il4v.jpg",
  "Overhaul_bronze_ultra_sp_450k.jpg": "https://files.catbox.moe/bfmk4u.jpg",
  "Pain_argent_ultra_sm_700k.jpg": "https://files.catbox.moe/mjxjao.jpg",
  "Panda_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/lqbo0t.jpg",
  "Patolli_or_ultra_sm_1m.jpg": "https://files.catbox.moe/kapj43.jpg",
  "Pegasus_or_legende_ssp_500nc.jpg": "https://files.catbox.moe/1353bb.jpg",
  "Piccolo(Fusion)_argent_ultra_ss_200nc.jpg": "https://files.catbox.moe/z17dbx.jpg",
  "Piccolo_bronze_sparking_ssm_100nc.jpg": "https://files.catbox.moe/vmzg90.jpg",
  "Polnareff_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/xha2ko.jpg",
  "Pucci_argent_legend_sm_1M.jpg": "https://files.catbox.moe/61eiyg.jpg",
  "Raccoon_bronze_sparking_ssp_90nc.jpg": "https://files.catbox.moe/saiqjf.jpg",
  "Radamanthys_or_sparking_sp_1M500k.jpg": "https://files.catbox.moe/dk68wa.jpg",
  "Raditz_bronze_sparking_ssm_110nc.jpg": "https://files.catbox.moe/r1ltde.jpg",
  "Rengoku_bronze_ultra_s_300k.jpg": "https://files.catbox.moe/tv23rh.jpg",
  "Rhya_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/ok93zn.jpg",
  "Robin_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/du8m3n.jpg",
  "Rogue_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/yofjr9.jpg",
  "Rui_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/y1uty1.jpg",
  "Ryu_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/gjbi4u.jpg",
  "Sabo_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/38qeen.jpg",
  "Saga_or_ultra_sp_2M.jpg": "https://files.catbox.moe/1qtha5.jpg",
  "Sai_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/dg8f61.jpg",
  "Saitama_or_legend_ssp_300nc.jpg": "https://files.catbox.moe/kskpcn.jpg",
  "Sakura(4GG)_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/s64n58.jpg",
  "Sakura_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/a10aqp.jpg",
  "Sanemi_bronze_ultra_s_300k.jpg": "https://files.catbox.moe/nbat3b.jpg",
  "Sanji_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/dx9mlf.jpg",
  "Sarada_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/0gmxiu.jpg",
  "Sasori_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/230r8w.jpg",
  "Sasuke(EMS)_argent_legend_s_800k.jpg": "https://files.catbox.moe/pia2pc.jpg",
  "Sasuke(Taka)_argent_ultra_sm_600k.jpg": "https://files.catbox.moe/7kbi9l.jpg",
  "Sasuke_bronze_ultra_sp_400k.jpg": "https://files.catbox.moe/1qsskp.jpg",
  "Sasuke(Hebi)_bronze_ultra_sp_450k.jpg": "https://files.catbox.moe/cwaaa7.jpg",
  "Sasuke(Akatsuki)_bronze_ultra_sp_500k.jpg": "https://files.catbox.moe/uxne57.jpg",
  "Sasuke(SP)_or_legend_sm_1M200k.jpg": "https://files.catbox.moe/7d0flm.jpg",
  "Sasuke(Shinden)_or_legend_sm_1m200k.jpg": "https://files.catbox.moe/haef5r.jpg",
  "Sasuke(Boruto)_or_legende_sm_1M.jpg": "https://files.catbox.moe/9bduze.jpg",
  "Seiya_argent_ultra_s_800k.jpg": "https://files.catbox.moe/epeq5l.jpg",
  "Shaka_or_legende_sm_2M500k.jpg": "https://files.catbox.moe/ehburs.jpg",
  "Shanks_or_legend_sm_1M.jpg": "https://files.catbox.moe/17r2x4.jpg",
  "Shigaraki_argent_ultra_s_700k.jpg": "https://files.catbox.moe/jqjscv.jpg",
  "Shikadai_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/fn3b4a.jpg",
  "Shikamaru_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/olrdcv.jpg",
  "Shiki_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/iz2ttd.jpg",
  "Shin_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/n977zq.jpg",
  "Shino_bronze_spatking_sm_100k.jpg": "https://files.catbox.moe/o4izh4.jpg",
  "Shinobu_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/kqej55.jpg",
  "Shinso_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/z5mpoh.jpg",
  "Shiryu_argent_sparking_s_800k.jpg": "https://files.catbox.moe/tsh66g.jpg",
  "Shisui_argent_legend_sm_700k.jpg": "https://files.catbox.moe/gdcvd8.jpg",
  "Shoto_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/3cfj4z.jpg",
  "Shun_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/ndxmd6.jpg",
  "Silva_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/p7p2e3.jpg",
  "Sonic_bronze_sparking_sp_400k.jpg": "https://files.catbox.moe/jzy3gr.jpg",
  "Stain_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/l7ermt.jpg",
  "StarAndStripes_argent_ultra_s_100nc.jpg": "https://files.catbox.moe/blqhww.jpg",
  "Sting_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/t869qh.jpg",
  "Suigetsu_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/1p68ff.jpg",
  "Suiryu_bronze_sparking_sp_400k.jpg": "https://files.catbox.moe/agtxsf.jpg",
  "SuperAndroid17_or_legend_ssp_380nc.jpg": "https://files.catbox.moe/mjnton.jpg",
  "Vegeta(Super)_argent_legend_ssp_250nc.jpg": "https://files.catbox.moe/ktvi11.jpg",
  "Susamaru_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/fin05s.jpg",
  "Tanjiro(Demon)_argent_legend_sm_50nc.jpg": "https://files.catbox.moe/xlwdvp.jpg",
  "Tanjiro(debut)_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/aq59kx.jpg",
  "Tanjiro_bronze_ultra_s_300k.jpg": "https://files.catbox.moe/y3pnjx.jpg",
  "TanktopMarcel_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/xxfbj7.jpg",
  "Tatako_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/d1ypx9.jpg",
  "Tatsumaki_or_legend_sm_1m.jpg": "https://files.catbox.moe/4puqzw.jpg",
  "Teach_argent_legend_sm_1M.jpg": "https://files.catbox.moe/khap3e.jpg",
  "Temari_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/lvnx8y.jpg",
  "Tengen_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/vg4cyw.jpg",
  "Tenshinhan_bronze_ultra_sp_600k.jpg": "https://files.catbox.moe/binc1i.jpg",
  "Tenten_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/hhl7t4.jpg",
  "Tenya_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/y5u0vt.jpg",
  "Thales_bronze_sparking_ssp_110nc.jpg": "https://files.catbox.moe/ljrcbk.jpg",
  "Thanatos_or_legende_ssp_400nc.jpg": "https://files.catbox.moe/gycytd.jpg",
  "Tobi(4GG)_argent_legend_s_800k.jpg": "https://files.catbox.moe/yde4i0.jpg",
  "Tobirama_argent_legend_sp_900k.jpg": "https://files.catbox.moe/lomjn4.jpg",
  "Toga_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/pvg87z.jpg",
  "Toge_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/818k07.jpg",
  "Toji_argent_ultra_sm_600k.jpg": "https://files.catbox.moe/mo6e5z.jpg",
  "Toneri_argent_ultra_sp_1m.jpg": "https://files.catbox.moe/nrog1q.jpg",
  "Toppo_or_ultra_ssp_420nc.jpg": "https://files.catbox.moe/fhqr3r.jpg",
  "Trunks(kid)_argent_sparking_ssm_150nc.jpg": "https://files.catbox.moe/ptpckm.jpg",
  "Trunks_argent_sparking_ssm_200nc.jpg": "https://files.catbox.moe/alprgr.jpg",
  "Trunks(Futur)_argent_ultra_ssm_170nc.jpg": "https://files.catbox.moe/ougnbx.jpg",
  "Trunks(Dbs)_argent_ultra_ssp_230nc.jpg": "https://files.catbox.moe/zicnsn.jpg",
  "Tsunade_bronze_ultra_s_400k.jpg": "https://files.catbox.moe/nlggb9.jpg",
  "Twice_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/rk9zp5.jpg",
  "Uraume_argent_ultra_sm_500k.jpg": "https://files.catbox.moe/mugdkc.jpg",
  "Vanessa_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/kyael1.jpg",
  "Vanica_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/dekzwe.jpg",
  "Vegeta(SSJ)_argent_ultra_ssm_180nc.jpg": "https://files.catbox.moe/k2cdjt.jpg",
  "Vegeta(Tracker)_bronze_sparking_ssp_130nc.jpg": "https://files.catbox.moe/swz65c.jpg",
  "Vegeta(SSJ4)_or_legend_ss_340nc.jpg": "https://files.catbox.moe/fgqu2w.jpg",
  "Vegeta(SSJBlue)_or_legend_ssp_450nc.jpg": "https://files.catbox.moe/l3gss8.jpg",
  "Vegeta(UE)_or_legend_ssp_550nc.jpg": "https://files.catbox.moe/b9svgt.jpg",
  "Vegeta(SSJGod)_or_ultra_ssp_420nc.jpg": "https://files.catbox.moe/7pznu1.jpg",
  "Vegito(Dbz) _or_legend_ssp_450nc.jpg": "https://files.catbox.moe/rgybyi.jpg",
  "Vegito(DbS)_or_legend_ssp_550nc.jpg": "https://files.catbox.moe/wujmrs.jpg",
  "Vengeance_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/aupjwj.jpg",
  "Vetto_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/xp0i8c.jpg",
  "Victor_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/m3hq7x.jpg",
  "Videl_bronze_sparking_sp_500k.jpg": "https://files.catbox.moe/0mubo7.jpg",
  "Weatherreport_argent_ultra_sm_900k.jpg": "https://files.catbox.moe/eq2wxq.jpg",
  "Wendy_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/uowygv.jpg",
  "Yahaba_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/jqa4l1.jpg",
  "Yamato_bronze_sparking_s_300k.jpg": "https://files.catbox.moe/ngy97w.jpg",
  "Yamcha_bronze_sparking_sp_500k.jpg": "https://files.catbox.moe/03fmv6.jpg",
  "Yami_argent_legend_s_50nc.jpg": "https://files.catbox.moe/alpzdx.jpg",
  "Yorozu_argent_sparking_sm_500k.jpg": "https://files.catbox.moe/zydytg.jpg",
  "Yuji(Shibuya)_bronze_sparking_s_200k.jpg": "https://files.catbox.moe/w0j4ll.jpg",
  "Yuji(Shinjuku)_argent_sparking_sm_50nc.jpg": "https://files.catbox.moe/q3yidh.jpg",
  "Yuji_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/dh6evb.jpg",
  "Yuki_argent_ultra_sm_500k.jpg": "https://files.catbox.moe/16a2yx.jpg",
  "Yuno_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/v3bnlo.jpg",
  "Yuta_bronze_legend_sp_400k.jpg": "https://files.catbox.moe/06fvgx.jpg",
  "Yuta(Shinjuku)_argent_ultra_sm_50nc.jpg": "https://files.catbox.moe/pm6ioo.jpg",
  "Zabuza_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/44fdv2.jpg",
  "Zamasu_or_legend_ssp_520nc.jpg": "https://files.catbox.moe/163ro4.jpg",
  "Zenitsu_bronze_sparking_sm_200k.jpg": "https://files.catbox.moe/fqil2d.jpg",
  "Zeno_bronze_sparking_sp_400k.jpg": "https://files.catbox.moe/cem49v.jpg",
  "Zenon_or_ultra_sm_1m.jpg": "https://files.catbox.moe/ezuqry.jpg",
  "Zeref_argent_sparking_s_500k.jpg": "https://files.catbox.moe/7than2.jpg",
  "Zohakuten_bronze_ultra_sp_400k.jpg": "https://files.catbox.moe/1yh0jf.jpg",
  "Zora_bronze_sparking_sm_100k.jpg": "https://files.catbox.moe/dgoqx7.jpg",
  "Zorro_argent_ultra_sm_500k.jpg": "https://files.catbox.moe/h2cvdu.jpg"
};

function determinePrice(pricePart) {
  pricePart = pricePart.toLowerCase();
  if (pricePart.endsWith('nc')) {
    return pricePart.replace('nc', '🔷');
  }
  let total = 0;
  const priceRegex = /(\d+)([km]?)/g;
  let match;
  while ((match = priceRegex.exec(pricePart)) !== null) {
    const value = parseInt(match[1]);
    const unit = match[2];
    if (unit === 'k') {
      total += value * 1000;
    } else if (unit === 'm') {
      total += value * 1000000;
    } else {
      total += value;
    }
  }
  return total.toLocaleString() + '🧭';
}

function determineCategory(categoryPart) {
  switch (categoryPart) {
    case 'sm': return 's-';
    case 'sp': return 's+';
    case 's': return 's';
    case 'ssm': return 'ss-';
    case 'ssp': return 'ss+';
    case 'ss': return 'ss';
    default: return 'inconnu';
  }
}

function createCard(fileName, imageUrl) {
  const parts = fileName.replace('.jpg', '').split('_');
  const name = parts[0];
  const grade = parts[1];
  let placement = parts[2];
  if (placement === 'legende' || placement === 'card_legende') {
    placement = 'legend';
  }
  const category = determineCategory(parts[3]);
  const price = determinePrice(parts[4]);
  return {
    name,
    grade,
    placement,
    category,
    price,
    image: imageUrl
  };
}

function groupCardsByPlacement(cardsArray) {
  const groupedCards = {};
  for (const card of cardsArray) {
    const placement = card.placement;
    if (!groupedCards[placement]) {
      groupedCards[placement] = [];
    }
    groupedCards[placement].push({
      grade: card.grade,
      name: card.name,
      category: card.category,
      image: card.image,
      price: card.price
    });
  }
  return groupedCards;
}

function generateCardsFromObject(cardsObject) {
  const allCards = [];
  for (const [fileName, url] of Object.entries(cardsObject)) {
    if (fileName.endsWith('.jpg')) {
      const card = createCard(fileName, url);
      allCards.push(card);
    }
  }
  return groupCardsByPlacement(allCards);
}

const cardData = generateCardsFromObject(cards);
module.exports = { cards: cardData };
